In [66]:
import torch
import torch.nn as nn

In [19]:

torch.Tensor([[ 1,  2,  3,  4]]).shape

torch.Size([1, 4])

In [40]:
class Similarity(torch.nn.Module):
    """
    Dot product or cosine similarity
    """
    def __init__(self, temp=0.05):
        super().__init__()
        self.temp = temp
        self.cos = torch.nn.CosineSimilarity(dim=-1)

    def forward(self, x, y):
        return self.cos(x, y) / self.temp

In [73]:
z1 = torch.FloatTensor([[[1, 2, 4]],[[1, 2, 4]]])
z2 = torch.FloatTensor([[[1, 2, 4]],[[1, 2, 4]]])

uns_z1 = torch.unsqueeze(z1, 1)
uns_z2 = torch.unsqueeze(z2, 0)
print('z1:', z1.shape)
print(uns_z1.shape)
print(uns_z2.shape)

z1: torch.Size([2, 1, 3])
torch.Size([2, 1, 1, 3])
torch.Size([1, 2, 1, 3])


In [74]:
sim = Similarity()

In [75]:
cos_sim = sim(uns_z1, uns_z2)
cos_sim

tensor([[[20.0000],
         [20.0000]],

        [[20.0000],
         [20.0000]]])

In [60]:
result.shape

torch.Size([2, 2, 1])

In [61]:
torch.cat([cos_sim, cos_sim], 1).shape

torch.Size([2, 4, 1])

In [65]:
cos_sim

tensor([[[20.0000],
         [20.0000]],

        [[20.0000],
         [20.0000]]])

In [63]:
labels = torch.arange(cos_sim.size(0)).long()
labels.shape

torch.Size([2])

In [64]:
labels

tensor([0, 1])

In [ ]:
def cross_entropy(
    input: Tensor,
    target: Tensor,
    weight: Optional[Tensor] = None,
    size_average: Optional[bool] = None,
    ignore_index: int = -100,
    reduce: Optional[bool] = None,
    reduction: str = "mean",
    label_smoothing: float = 0.0,
) -> Tensor:

    if has_torch_function_variadic(input, target, weight):
        return handle_torch_function(
            cross_entropy,
            (input, target, weight),
            input,
            target,
            weight=weight,
            size_average=size_average,
            ignore_index=ignore_index,
            reduce=reduce,
            reduction=reduction,
            label_smoothing=label_smoothing,
        )
    if size_average is not None or reduce is not None:
        reduction = _Reduction.legacy_get_string(size_average, reduce)
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)


In [ ]:
class CrossEntropyLoss(_WeightedLoss):
    __constants__ = ['ignore_index', 'reduction', 'label_smoothing']
    ignore_index: int
    label_smoothing: float

    def __init__(self, weight: Optional[Tensor] = None, size_average=None, ignore_index: int = -100,
                 reduce=None, reduction: str = 'mean', label_smoothing: float = 0.0) -> None:
        super(CrossEntropyLoss, self).__init__(weight, size_average, reduce, reduction)
        self.ignore_index = ignore_index
        self.label_smoothing = label_smoothing

    def forward(self, input: Tensor, target: Tensor) -> Tensor:
        return F.cross_entropy(input, target, weight=self.weight,
                               ignore_index=self.ignore_index, reduction=self.reduction,
                               label_smoothing=self.label_smoothing)



In [ ]:
loss_fct = nn.CrossEntropyLoss()

In [ ]:
loss = loss_fct(cos_sim, labels)